In [2]:
import pandas as pd
from os import listdir
from os.path import isfile, join

In [4]:
print(pd.__version__)

1.3.4

In [28]:
import datetime
import time

todaysDate = datetime.date.today();
print(datetime.date.today().year)

2022

In [46]:
path = "C:\\Users\\Francis John Picaso\\Repositories\\Teo\\logs\\"
onlyfiles = [path + f for f in listdir(path) if isfile(join(path, f))]
onlyfiles

['C:\\Users\\Francis John Picaso\\Repositories\\Teo\\logs\\\\GeneralLog1350185-220110.log',
 'C:\\Users\\Francis John Picaso\\Repositories\\Teo\\logs\\\\GeneralLog1350185-220111.log',
 'C:\\Users\\Francis John Picaso\\Repositories\\Teo\\logs\\\\GeneralLog1350185-220112.log',
 'C:\\Users\\Francis John Picaso\\Repositories\\Teo\\logs\\\\GeneralLog1350185-220113.log',
 'C:\\Users\\Francis John Picaso\\Repositories\\Teo\\logs\\\\GeneralLog1350185-220114.log']

In [29]:
ParseLog(path)

['GeneralLog1350185-220110.log', 'GeneralLog1350185-220111.log', 'GeneralLog1350185-220112.log', 'GeneralLog1350185-220113.log', 'GeneralLog1350185-220114.log']

In [31]:
ParseLog(path,isFolder='N')

is a file

In [28]:
def ParseLog(path,isFolder='Y'):
    if isFolder == 'Y':
        onlyfiles = [f for f in listdir(path) if isfile(join(path, f))]
        print(onlyfiles)
    else:
        print("is a file")

In [44]:
import pandas as pd

class LogParser():
    def __init__(self,path,isFolder):
        self.path = path
        self.isFolder = isFolder
        columns = ['Timestamp', 'Log Message', 'Message', 'User Path', 'Customer Path','Lot ID', 'Wafer ID', 'Port ID', 'Date', 'Time']
        df = pd.DataFrame(columns=columns)
        self.parsedLog = df
        
    def ParseLogs(self,file):
        #placeholder columns to get all data

        columnPlaceholder = [
            'Event Type',
            'Timestamp',
            'Log Message',
            'Category',
            'User',
            'Thread ID',
            'Error Code',
            'Application',
            'Machine'
        ]
        columnPlaceholder = columnPlaceholder + ['col' + str(i) for i in range(100)]
        df = pd.read_csv(file, sep='\t', lineterminator='\n',names=columnPlaceholder)
        
        #step 1
        #Table.RemoveColumns({"Error Code", "Application", "Machine", "Category", "Event Type", "Thread ID", "User", "Source.Name"})
        step1 = df.drop(["Error Code", "Application", "Machine", "Category", "Event Type", "Thread ID", "User"],axis=1)

In [45]:
parser = LogParser(path=path,isFolder = 'Y')
parser.parsedLog

initial Class

Empty DataFrame
Columns: [Timestamp, Log Message, Message, User Path, Customer Path, Lot ID, Wafer ID, Port ID, Date, Time]
Index: []

In [3]:

path = "C:\\Users\\Francis John Picaso\\Repositories\\Teo\\GeneralLog1350185-220424.log"
df = pd.read_csv(path, sep='\t', lineterminator='\n',on_bad_lines='skip')
df

                                                                                                                                                       KTLogging Service\r
Event Type    Timestamp               Log Message                                        Category              User   Thread ID Error Code Application           Machine\r
<information> 2022-04-24 00:14:08.837 HEADER: 2022-04-19 10:19:24.472~Version 10.10.6... NaN                   NaN    NaN       NaN        NaN                          \r
<trace>       2022-04-24 00:14:08.761 Low Disk Space, Overriding schedule rule for cl... MainUI.General_System kttool 10744     0x0        MainUI              1350185IS\r
<information> 2022-04-24 00:14:08.781 Available Disk space : 101831 MB                   MainUI.General_System kttool 8152      0x0        MainUI              1350185IS\r
              2022-04-24 00:14:19.585 Time taken for cleanup : 00:00:11                  MainUI.General_System kttool 8152      0x0        MainUI              1350185IS\r
...                                                                                                                                                                    ...
<trace>       2022-04-24 23:59:58.930 DoRun - Attempting to save 3212defects' images ... MainUI.General_System kttool 12136     0x0        MainUI              1350185IS\r
                                      DoRun - Number of images to be saved - 10266 im... MainUI.General_System kttool 12136     0x0        MainUI              1350185IS\r
              2022-04-24 23:59:59.217 DoRun - Accumulated Images Saved<Pass Run - Lot... MainUI.General_System kttool 12136     0x0        MainUI              1350185IS\r
                                      Memory load: 54, Free RAM: 14870 MB, Free virtu... MainUI.General_System kttool 12136     0x0        MainUI              1350185IS\r
                                      DoRun - #defects (PlPrNuQu): 19317 19317 0 0       MainUI.General_System kttool 12136     0x0        MainUI              1350185IS\r

[2302 rows x 1 columns]

In [4]:
#placeholder columns to get all data

columnPlaceholder = [
    'Event Type',
    'Timestamp',
    'Log Message',
    'Category',
    'User',
    'Thread ID',
    'Error Code',
    'Application',
    'Machine'
]
columnPlaceholder = columnPlaceholder + ['col' + str(i) for i in range(100)]
path = "C:\\Users\\Francis John Picaso\\Repositories\\Teo\\GeneralLog1350185-220424.log"
df = pd.read_csv(path, sep='\t', lineterminator='\n',names=columnPlaceholder)
df

,Event Type,Timestamp,Log Message,Category,User,Thread ID,Error Code,Application,Machine,col0,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
0,KTLogging Service\r,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Event Type,Timestamp,Log Message,Category,User,Thread ID,Error Code,Application,Machine\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,<information>,2022-04-24 00:14:08.837,HEADER: 2022-04-19 10:19:24.472~Version 10.10....,NaN,NaN,NaN,NaN,NaN,\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,<trace>,2022-04-24 00:14:08.761,"Low Disk Space, Overriding schedule rule for c...",MainUI.General_System,kttool,10744,0x0,MainUI,1350185IS\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,<information>,2022-04-24 00:14:08.781,Available Disk space : 101831 MB,MainUI.General_System,kttool,8152,0x0,MainUI,1350185IS\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2310,<trace>,2022-04-24 23:59:58.930,DoRun - Attempting to save 3212defects' images...,MainUI.General_System,kttool,12136,0x0,MainUI,1350185IS\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2311,<trace>,2022-04-24 23:59:58.930,DoRun - Number of images to be saved - 10266 i...,MainUI.General_System,kttool,12136,0x0,MainUI,1350185IS\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2312,<trace>,2022-04-24 23:59:59.217,DoRun - Accumulated Images Saved<Pass Run - Lo...,MainUI.General_System,kttool,12136,0x0,MainUI,1350185IS\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2313,<trace>,2022-04-24 23:59:59.217,"Memory load: 54, Free RAM: 14870 MB, Free virt...",MainUI.General_System,kttool,12136,0x0,MainUI,1350185IS\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2314,<trace>,2022-04-24 23:59:59.217,DoRun - #defects (PlPrNuQu): 19317 19317 0 0,MainUI.General_System,kttool,12136,0x0,MainUI,1350185IS\r,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#step 1
#Table.RemoveColumns({"Error Code", "Application", "Machine", "Category", "Event Type", "Thread ID", "User", "Source.Name"})
step1 = df.drop(["Error Code", "Application", "Machine", "Category", "Event Type", "Thread ID", "User"],axis=1)
step1

,Timestamp,Log Message,col0,col1,col2,col3,col4,col5,col6,col7,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Timestamp,Log Message,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-04-24 00:14:08.837,HEADER: 2022-04-19 10:19:24.472~Version 10.10....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-04-24 00:14:08.761,"Low Disk Space, Overriding schedule rule for c...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-04-24 00:14:08.781,Available Disk space : 101831 MB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2310,2022-04-24 23:59:58.930,DoRun - Attempting to save 3212defects' images...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2311,2022-04-24 23:59:58.930,DoRun - Number of images to be saved - 10266 i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2312,2022-04-24 23:59:59.217,DoRun - Accumulated Images Saved<Pass Run - Lo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2313,2022-04-24 23:59:59.217,"Memory load: 54, Free RAM: 14870 MB, Free virt...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2314,2022-04-24 23:59:59.217,DoRun - #defects (PlPrNuQu): 19317 19317 0 0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#step2 Table.SelectRows(each Text.StartsWith([Log Message], "Lot Run - Dumping special environment variables") or 
#Text.StartsWith([Log Message], "Lot Run - Lot Inspection Done") or 
#Text.StartsWith([Log Message], "Wafer Run - Time per wafer inspection ") and Text.EndsWith([Log Message], ">"))
step2 = step1[
    (step1["Log Message"].str.startswith('Lot Run - Dumping special environment variables',na=False))
    | (step1["Log Message"].str.startswith('Lot Run - Lot Inspection Done',na=False))
    | (step1["Log Message"].str.startswith('Wafer Run - Time per wafer inspection ',na=False))
    & (step1["Log Message"].str.endswith('>',na=False))
]
step2

,Timestamp,Log Message,col0,col1,col2,col3,col4,col5,col6,col7,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
1280,2022-04-24 23:39:20.705,Lot Run - Dumping special environment variable...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#step3 Table.ReplaceValue("Lot Run - Dumping special environment variables:<Lot Run -Lot name : ",
#"Lot Start <",
#Replacer.ReplaceText,{"Log Message"})
step2["Log Message"] = step2["Log Message"].str.replace(
    "Lot Run - Dumping special environment variables:<Lot Run -Lot name : ",
    "Lot Start <"
)
step2

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/2803813820.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step2["Log Message"] = step2["Log Message"].str.replace(

,Timestamp,Log Message,col0,col1,col2,col3,col4,col5,col6,col7,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#step4 Table.ReplaceValue(
#"Wafer Run - Time per wafer inspection = ",
#"Duration = ",Replacer.ReplaceText,{"Log Message"})

step2["Log Message"] = step2["Log Message"].str.replace(
    "Wafer Run - Time per wafer inspection = ",
    "Duration = "
)
step2

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1817509647.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step2["Log Message"] = step2["Log Message"].str.replace(

,Timestamp,Log Message,col0,col1,col2,col3,col4,col5,col6,col7,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#step5 Table.ReplaceValue(
#"Lot Run - Lot Inspection Done<Lot Run -Lot name : ",
#"Lot End <",Replacer.ReplaceText,{"Log Message"})
step2["Log Message"] = step2["Log Message"].str.replace(
    "Lot Run - Lot Inspection Done<Lot Run -Lot name : ",
    "Lot End <"
)
step2

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/4260061337.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step2["Log Message"] = step2["Log Message"].str.replace(

,Timestamp,Log Message,col0,col1,col2,col3,col4,col5,col6,col7,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#step6 Table.ReplaceValue(
#"<Wafer Run - Lot name: ",
#"<Wafer Run - Lot name: ",Replacer.ReplaceText,{"Log Message"})

step2["Log Message"] = step2["Log Message"].str.replace(
    "<Wafer Run - Lot name: ",
    "<Wafer Run - Lot name: "
)
step2

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/3349179075.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step2["Log Message"] = step2["Log Message"].str.replace(

,Timestamp,Log Message,col0,col1,col2,col3,col4,col5,col6,col7,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
logs = step2[["Timestamp","Log Message"]]
logs.head(10)

                    Timestamp                                     Log Message
1280  2022-04-24 23:39:20.705  Lot Start <USERS\Christophe\AT210295-OPER7651>

In [16]:
#step7 Table.SplitColumn("Log Message", Splitter.SplitTextByEachDelimiter({"<"}, QuoteStyle.Csv, false), {"Log Message.1", "Log Message.2"})
logs[["Log Message.1", "Log Message.2"]] = logs['Log Message'].str.split('<', expand=True)
logs.head(10)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,Timestamp,Log Message,Log Message.1,Log Message.2
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651>

In [17]:
#step8 Table.ReplaceValue("Wafer Run - Lot name: ","<",Replacer.ReplaceText,{"Log Message.2"})
logs["Log Message.2"] = logs["Log Message.2"].str.replace(
    "Wafer Run - Lot name: ",
    "<"
)
logs.head(10)

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1278831361.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  logs["Log Message.2"] = logs["Log Message.2"].str.replace(

,Timestamp,Log Message,Log Message.1,Log Message.2
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651>

In [18]:
#step9 Table.ReplaceValue("<","",Replacer.ReplaceText,{"Log Message.2"})
logs["Log Message.2"] = logs["Log Message.2"].str.replace(
    "<",
    ""
)
logs.head(10)

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/3880868075.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  logs["Log Message.2"] = logs["Log Message.2"].str.replace(

,Timestamp,Log Message,Log Message.1,Log Message.2
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651>

In [19]:
#step10 Table.ReplaceValue("Duration = ","",Replacer.ReplaceText,{"Log Message.1"})
logs["Log Message.1"] = logs["Log Message.1"].str.replace(
    "Duration = ",
    ""
)
logs.head(10)

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1860991219.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  logs["Log Message.1"] = logs["Log Message.1"].str.replace(

,Timestamp,Log Message,Log Message.1,Log Message.2
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651>

In [20]:
#step11 Table.ReplaceValue(">","",Replacer.ReplaceText,{"Log Message.2"})
logs["Log Message.2"] = logs["Log Message.2"].str.replace(
    ">",
    ""
)
logs.head(10)

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/2330621383.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  logs["Log Message.2"] = logs["Log Message.2"].str.replace(

,Timestamp,Log Message,Log Message.1,Log Message.2
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651

In [21]:
#Step12 Table.SplitColumn("Log Message.2", Splitter.SplitTextByDelimiter("\", QuoteStyle.Csv), {"Log Message.2.2", "Log Message.2.3"})

logs[["Log Message.2.1","Log Message.2.2", "Log Message.2.3"]] = logs['Log Message.2'].str.split("\\", expand=True)
logs

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,Timestamp,Log Message,Log Message.1,Log Message.2,Log Message.2.1,Log Message.2.2,Log Message.2.3
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651,USERS,Christophe,AT210295-OPER7651

In [33]:
#step13 Table.SplitColumn("Log Message.2.3", Splitter.SplitTextByEachDelimiter({"Wafer ID: "}, QuoteStyle.Csv, false), {"Log Message.2.3.1", "Log Message.2.3.2"})
try:
    logs[["Log Message.2.3.1","Log Message.2.3.2"]] = logs['Log Message.2.3'].str.split("Wafer ID: ", expand=True)
except ValueError:
    logs["Log Message.2.3.1"] = logs['Log Message.2.3']
    logs["Log Message.2.3.2"] = ""
    
logs

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1959821463.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  logs["Log Message.2.3.1"] = logs['Log Message.2.3']
C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1959821463.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  logs["Log Message.2.3.2"] = ""

,Timestamp,Log Message,Log Message.1,Log Message.2,Log Message.2.1,Log Message.2.2,Log Message.2.3,Log Message.2.3.1,Log Message.2.3.2
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651,USERS,Christophe,AT210295-OPER7651,AT210295-OPER7651,

In [35]:
#step14 Table.SplitColumn("Log Message.2.3.2", Splitter.SplitTextByEachDelimiter({"Port No: "}, QuoteStyle.Csv, false), {"Log Message.2.3.2.1", "Log Message.2.3.2.2"})
try:
    logs[["Log Message.2.3.2.1","Log Message.2.3.2.2"]] = logs['Log Message.2.3.2'].str.split("Port No: ", expand=True)
except ValueError:
    logs["Log Message.2.3.2.1"] = logs['Log Message.2.3.2']
    logs["Log Message.2.3.2.2"] = ""
    
logs

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/3858238902.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  logs["Log Message.2.3.2.1"] = logs['Log Message.2.3.2']
C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/3858238902.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  logs["Log Message.2.3.2.2"] = ""

,Timestamp,Log Message,Log Message.1,Log Message.2,Log Message.2.1,Log Message.2.2,Log Message.2.3,Log Message.2.3.1,Log Message.2.3.2,Log Message.2.3.2.1,Log Message.2.3.2.2
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651,USERS,Christophe,AT210295-OPER7651,AT210295-OPER7651,,,

In [36]:
#step 15 
"""
Table.RenameColumns({
#{"Log Message.2.3.2.1", "Wafer ID"}, 
#{"Log Message.2.3.2.2", "Port ID"}, 
#{"Log Message.2.3.1", "Lot ID"}, 
#{"Log Message.2.2", "Customer Path"}, 
#{"Log Message.2.1", "User Path"}, 
#{"Log Message.1", "Message"}})
"""
logs.rename(columns = {
    "Log Message.2.3.2.1": "Wafer ID", 
    "Log Message.2.3.2.2": "Port ID", 
    "Log Message.2.3.1": "Lot ID", 
    "Log Message.2.2": "Customer Path", 
    "Log Message.2.1": "User Path", 
    "Log Message.1": "Message"
}, inplace = True)
logs

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,Timestamp,Log Message,Message,Log Message.2,User Path,Customer Path,Log Message.2.3,Lot ID,Log Message.2.3.2,Wafer ID,Port ID
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS\Christophe\AT210295-OPER7651,USERS,Christophe,AT210295-OPER7651,AT210295-OPER7651,,,

In [37]:
columns = [col for col in logs.columns if col not in ["Log Message.2","Log Message.2.3","Log Message.2.3.2"]]
step16 = logs[columns]
step16

,Timestamp,Log Message,Message,User Path,Customer Path,Lot ID,Wafer ID,Port ID
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS,Christophe,AT210295-OPER7651,,

In [38]:
step16["Timestamp"] = pd.to_datetime(step16.Timestamp)
step16["Date"] = step16['Timestamp'].dt.date
step16["Date"] = pd.to_datetime(step16.Date)
step16["Time"] = step16['Timestamp'].dt.time
print(step16.dtypes)
step16.head(10)

Timestamp        datetime64[ns]
Log Message              object
Message                  object
User Path                object
Customer Path            object
Lot ID                   object
Wafer ID                 object
Port ID                  object
Date             datetime64[ns]
Time                     object
dtype: object

C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1480304469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step16["Timestamp"] = pd.to_datetime(step16.Timestamp)
C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1480304469.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step16["Date"] = step16['Timestamp'].dt.date
C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1480304469.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step16["Date"] = pd.to_datetime(step16.Date)
C:\Users\FRANCI~1\AppData\Local\Temp/ipykernel_26568/1480304469.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step16["Time"] = step16['Timestamp'].dt.time

,Timestamp,Log Message,Message,User Path,Customer Path,Lot ID,Wafer ID,Port ID,Date,Time
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS,Christophe,AT210295-OPER7651,,,2022-04-24,23:39:20.705000

In [39]:
step16.head(10)

,Timestamp,Log Message,Message,User Path,Customer Path,Lot ID,Wafer ID,Port ID,Date,Time
1280,2022-04-24 23:39:20.705,Lot Start <USERS\Christophe\AT210295-OPER7651>,Lot Start,USERS,Christophe,AT210295-OPER7651,,,2022-04-24,23:39:20.705000

In [24]:
step16

,Timestamp,Log Message,Message,User Path,Customer Path,Lot ID,Wafer ID,Port ID,Date,Time
2027,2022-01-10 16:03:18.371,Lot Start <DSW\Matching_Completed\a09bfbb_PM>,Lot Start,DSW,Matching_Completed,a09bfbb_PM,None,None,2022-01-10,16:03:18.371000
2419,2022-01-10 16:05:36.994,Duration = 00:01:48<Wafer Run - Lot name: DSW\...,00:01:48,DSW,Matching_Completed,a09bfbb_PM.,@10@001.,1,2022-01-10,16:05:36.994000
2673,2022-01-10 16:06:57.678,Duration = 00:01:21<Wafer Run - Lot name: DSW\...,00:01:21,DSW,Matching_Completed,a09bfbb_PM.,@10@002.,1,2022-01-10,16:06:57.678000
2976,2022-01-10 16:08:20.498,Duration = 00:01:22<Wafer Run - Lot name: DSW\...,00:01:22,DSW,Matching_Completed,a09bfbb_PM.,@10@003.,1,2022-01-10,16:08:20.498000
3033,2022-01-10 16:08:31.005,Lot End <DSW\Matching_Completed\a09bfbb_PM>,Lot End,DSW,Matching_Completed,a09bfbb_PM,None,None,2022-01-10,16:08:31.005000
3088,2022-01-10 16:08:32.722,Lot Start <DSW\Matching_Completed\a09bfbbhh_PM>,Lot Start,DSW,Matching_Completed,a09bfbbhh_PM,None,None,2022-01-10,16:08:32.722000
3476,2022-01-10 16:10:37.250,Duration = 00:01:38<Wafer Run - Lot name: DSW\...,00:01:38,DSW,Matching_Completed,a09bfbbhh_PM.,@10@001.,1,2022-01-10,16:10:37.250000
3730,2022-01-10 16:11:56.758,Duration = 00:01:19<Wafer Run - Lot name: DSW\...,00:01:19,DSW,Matching_Completed,a09bfbbhh_PM.,@10@002.,1,2022-01-10,16:11:56.758000
4031,2022-01-10 16:13:21.430,Duration = 00:01:23<Wafer Run - Lot name: DSW\...,00:01:23,DSW,Matching_Completed,a09bfbbhh_PM.,@10@003.,1,2022-01-10,16:13:21.430000
4087,2022-01-10 16:13:32.125,Lot End <DSW\Matching_Completed\a09bfbbhh_PM>,Lot End,DSW,Matching_Completed,a09bfbbhh_PM,None,None,2022-01-10,16:13:32.125000
4283,2022-01-10 16:13:32.809,Lot Start <DSW\Matching_Completed\a09bfbbvv_PM>,Lot Start,DSW,Matching_Completed,a09bfbbvv_PM,None,None,2022-01-10,16:13:32.809000
4666,2022-01-10 16:15:37.388,Duration = 00:01:39<Wafer Run - Lot name: DSW\...,00:01:39,DSW,Matching_Completed,a09bfbbvv_PM.,@10@001.,1,2022-01-10,16:15:37.388000
4972,2022-01-10 16:16:57.429,Duration = 00:01:20<Wafer Run - Lot name: DSW\...,00:01:20,DSW,Matching_Completed,a09bfbbvv_PM.,@10@002.,1,2022-01-10,16:16:57.429000
5531,2022-01-10 16:18:18.301,Duration = 00:01:21<Wafer Run - Lot name: DSW\...,00:01:21,DSW,Matching_Completed,a09bfbbvv_PM.,@10@003.,1,2022-01-10,16:18:18.301000
5632,2022-01-10 16:18:29.563,Lot End <DSW\Matching_Completed\a09bfbbvv_PM>,Lot End,DSW,Matching_Completed,a09bfbbvv_PM,None,None,2022-01-10,16:18:29.563000
5775,2022-01-10 16:18:30.256,Lot Start <DSW\Matching_Completed\a09bfudb_PM>,Lot Start,DSW,Matching_Completed,a09bfudb_PM,None,None,2022-01-10,16:18:30.256000
6229,2022-01-10 16:20:24.174,Duration = 00:01:28<Wafer Run - Lot name: DSW\...,00:01:28,DSW,Matching_Completed,a09bfudb_PM.,@10@001.,1,2022-01-10,16:20:24.174000
6388,2022-01-10 16:21:49.732,Duration = 00:01:24<Wafer Run - Lot name: DSW\...,00:01:24,DSW,Matching_Completed,a09bfudb_PM.,@10@002.,1,2022-01-10,16:21:49.732000
6544,2022-01-10 16:23:13.875,Duration = 00:01:22<Wafer Run - Lot name: DSW\...,00:01:22,DSW,Matching_Completed,a09bfudb_PM.,@10@003.,1,2022-01-10,16:23:13.875000
6601,2022-01-10 16:23:24.626,Lot End <DSW\Matching_Completed\a09bfudb_PM>,Lot End,DSW,Matching_Completed,a09bfudb_PM,None,None,2022-01-10,16:23:24.626000
6710,2022-01-10 16:23:26.481,Lot Start <DSW\Matching_Completed\a09vdsbb_PM>,Lot Start,DSW,Matching_Completed,a09vdsbb_PM,None,None,2022-01-10,16:23:26.481000
7099,2022-01-10 16:25:47.506,Duration = 00:01:54<Wafer Run - Lot name: DSW\...,00:01:54,DSW,Matching_Completed,a09vdsbb_PM.,@10@001.,1,2022-01-10,16:25:47.506000
7396,2022-01-10 16:27:05.198,Duration = 00:01:18<Wafer Run - Lot name: DSW\...,00:01:18,DSW,Matching_Completed,a09vdsbb_PM.,@10@002.,1,2022-01-10,16:27:05.198000
7647,2022-01-10 16:28:25.317,Duration = 00:01:20<Wafer Run - Lot name: DSW\...,00:01:20,DSW,Matching_Completed,a09vdsbb_PM.,@10@003.,1,2022-01-10,16:28:25.317000
7704,2022-01-10 16:28:36.657,Lot End <DSW\Matching_Completed\a09vdsbb_PM>,Lot End,DSW,Matching_Completed,a09vdsbb_PM,None,None,2022-01-10,16:28:36.657000
7819,2022-01-10 16:28:38.481,Lot Start <DSW\Matching_Completed\r09hcbb_PM>,Lot Start,DSW,Matching_Completed,r09hcbb_PM,None,None,2022-01-10,16:28:38.481000
8199,2022-01-10 16:30:55.431,Duration = 00:01:50<Wafer Run - Lot name: DSW\...,00:01:50,DSW,Matching_Completed,r09hcbb_PM.,@10@001.,1,2022-01-10,16:30:55.431000
8498,2022-01-10 16:32:09.231,Duration = 00:01:14<Wafer Run - Lot name: DSW\...,00:01:14,DSW,Matching_Completed,r09hcbb_PM.,@10@002.,1,2022-01-10,16:32:09.231000
8754,2022-01-10 16:33:26.176,Duration = 00:01:17<Wafer Run - Lot name: DSW\...,00:01:17,DSW,Matching_Completed,r09hcbb_PM.,@10@003.,1,2022-01-10,16:33:26.176000
8811,2022-01-10 16:33:37.316,Lot End <DSW\Matching_Completed\r09hcbb_PM>,Lot End,DSW,Matching_Completed,r09hcbb_PM,None,None,2022-01-10,16:33:37.316000
8946,2022-01-10 16:33:39.108,Lot Start <DSW\Matching_Completed\a05bfudb_PM>,Lot Start,DSW,Matching_Completed,a05bfudb_PM,None,None,2022-01-10,16:33:39.108000
9261,2022-01-10 16:35:04.983,Duration = 00:00:59<Wafer Run - Lot name: DSW\...,00:00:59,DSW,Matching_Completed,a05bfudb_PM.,@10@001.,1,2022-01-10,16:35:04.983000
9402,2022-01-10 16:36:01.605,Duration = 00:00:55<Wafer Run - Lot name: DSW\...,00:00:55,DSW,Matching_Completed,a05bfudb_PM.,@10@002.,1,2022-01-10,16:36:01.605000
9540,2022-01-10 16:36:58.502,Duration = 00:00:55<Wafer Run - Lot name: DSW\...,00:00:55,DSW,Matching_Completed,a05bfudb_PM.,@10@003.,1,2022-01-10,16:36:58.502000
9597,2022-01-10 16:37:09.595,Lot End <DSW\Matching_Completed\a05bfudb_PM>,Lot End,DSW,Matching_Completed,a05bfudb_PM,None,None,2022-01-10,16:37:09.595000
10351,2022-01-10 17:33:41.256,Lot Start <Monitor\KLA2925\SPC_10012022>,Lot Start,Monitor,KLA2925,SPC_10012022,None,None,2022-01-10,17:33:41.256000
13343,2022-01-10 18:04:18.610,Duration = 00:30:08<Wafer Run - Lot name: Moni...,00:30:08,Monitor,KLA2925,SPC_10012022.,D15@001.,2,2022-01-10,18:04:18.610000
13362,2022-01-10 18:04:18.619,Lot End <Monitor\KLA2925\SPC_10012022>,Lot End,Monitor,KLA2925,SPC_10012022,None,None,2022-01-10,18:04:18.619000
13810,2022-01-10 18:41:56.947,Lot Start <USERS\JSR\AR128172-7651>,Lot Start,USERS,JSR,AR128172-7651,None,None,2022-01-10,18:41:56.947000
20089,2022-01-10 18:50:35.068,Duration = 00:06:09<Wafer Run - Lot name: USER...,00:06:09,USERS,JSR,AR128172-7651.,@09@001.,2,2022-01-10,18:50:35.068000
20204,2022-01-10 18:50:53.918,Duration = 00:04:58<Wafer Run - Lot name: USER...,00:04:58,USERS,JSR,AR128172-7651.,@10@001.,2,2022-01-10,18:50:53.918000
20278,2022-01-10 18:51:02.825,Lot End <USERS\JSR\AR128172-7651>,Lot End,USERS,JSR,AR128172-7651,None,None,2022-01-10,18:51:02.825000
20347,2022-01-10 18:51:04.569,Lot Start <USERS\JSR\AR128172-F-7651>,Lot Start,USERS,JSR,AR128172-F-7651,None,None,2022-01-10,18:51:04.569000
20517,2022-01-10 18:52:02.545,Lot End <USERS\JSR\AR128172-F-7651>,Lot End,USERS,JSR,AR128172-F-7651,None,None,2022-01-10,18:52:02.545000
20571,2022-01-10 18:52:03.905,Lot Start <USERS\JSR\AR128172-D-7651>,Lot Start,USERS,JSR,AR128172-D-7651,None,None,2022-01-10,18:52:03.905000
20710,2022-01-10 18:52:38.006,Lot End <USERS\JSR\AR128172-D-7651>,Lot End,USERS,JSR,AR128172-D-7651,None,None,2022-01-10,18:52:38.006000
20805,2022-01-10 18:54:22.359,Lot Start <USERS\JSR\AR128172-C-7651>,Lot Start,USERS,JSR,AR128172-C-7651,None,None,2022-01-10,18:54:22.359000
22321,2022-01-10 19:00:43.548,Duration = 00:05:56<Wafer Run - Lot name: USER...,00:05:56,USERS,JSR,AR128172-C-7651.,@09@001.,1,2022-01-10,19:00:43.548000

In [38]:
step16.columns

Index(['Timestamp', 'Log Message', 'Message', 'User Path', 'Customer Path',
       'Lot ID', 'Wafer ID', 'Port ID', 'Date', 'Time'],
      dtype='object')